[package]
name = "chdig"
authors = ["Azat Khuzhin <a3at.mail@gmail.com>"]
homepage = "https://github.com/azat/chdig"
repository = "https://github.com/azat/chdig"
readme = "README.md"
description = "Dig into ClickHouse with TUI interface"
license = "MIT"
version = "0.5.0"
edition = "2021"

# TODO: convert this into feature set, but I'm not sure that it is easy right now (see [1]).
#  [1]: https://github.com/rust-lang/cargo/issues/1197
[target.'cfg(not(target_family = "windows"))'.dependencies]
cursive = { version = "*", default-features = false, features = ["termion-backend"] }
skim = "*"
[target.'cfg(target_family = "windows")'.dependencies]
# crossterm backend does not support Alt-<Key> bindings (interpret as just <Key>)
cursive = { version = "*", default-features = false, features = ["crossterm-backend"] }

[dependencies]
# Basic
anyhow = "*"
size = "*"
tempfile = "*"
url = "*"
humantime = "*"
backtrace = "*"
futures = "*"
# chrono/chrono-tz should match clickhouse-rs
chrono = "0.4"
chrono-tz = "0.8"
flexi_logger = "0.22"
log = "0.4"
futures-util = "*"
semver = "*"
stopwatch = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = { version = "*" }
quick-xml = { version = "*", features = ["serialize"] }
urlencoding = "*"
warp = "*"
# CLI
clap = { version = "*", features = ["derive", "env"] }
clap_complete = { version = "*" }
# UI
cursive_buffered_backend = "0.6.1"
cursive-syntect = "*"
# Patches:
# - Change focus - https://github.com/BonsaiDen/cursive_table_view/pull/40
cursive_table_view = { git = "https://github.com/azat-rust/cursive_table_view", branch = "next" }
# Patches:
# - Fix for date format - https://github.com/deinstapel/cursive-flexi-logger-view/pull/13
cursive-flexi-logger-view = { git = "https://github.com/azat-rust/cursive-flexi-logger-view", branch = "next" }
syntect = "*"
#
# Drivers
#
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", branch = "async-await", features = ["tls"] }
tokio = { version = "*", features = ["full"] }

[dependencies.flameshow]
path = "contrib/flameshow"

[profile.release]
lto = true
