[package]
name = "chdig"
description = "Dig into ClickHouse with TUI interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Basic
anyhow = "*"
size = "*"
tempfile = "*"
url = "*"
humantime = "*"
backtrace = "*"
# CLI
clap = { version = "*", features = ["derive", "env"] }
# UI
crossterm = "*"
cursive = "*"
cursive_table_view = "0.14"
skim = "*"
# Drivers
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs" }
tokio = { version = "*", features = ["full"] }
