[package]
name = "chdig"
authors = ["Azat Khuzhin <a3at.mail@gmail.com>"]
homepage = "https://github.com/azat/chdig"
repository = "https://github.com/azat/chdig"
readme = "README.md"
description = "Dig into ClickHouse with TUI interface"
license = "MIT"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Basic
anyhow = "*"
size = "*"
tempfile = "*"
url = "*"
humantime = "*"
backtrace = "*"
futures = "*"
# chrono/chrono-tz should match clickhouse-rs
chrono = "0.4"
chrono-tz = "0.8"
flexi_logger = "0.22"
log = "0.4"
futures-util = "*"
semver = "*"
stopwatch = "*"
serde = { version = "*", features = ["derive"] }
quick-xml = { version = "*", features = ["serialize"] }
urlencoding = "*"
warp = "*"
# CLI
clap = { version = "*", features = ["derive", "env"] }
# UI
ncurses = "*"
cursive = "*"
cursive-syntect = "*"
cursive_table_view = "0.14"
# Patches:
# - Fix for date format - https://github.com/deinstapel/cursive-flexi-logger-view/pull/13
cursive-flexi-logger-view = { git = "https://github.com/azat-rust/cursive-flexi-logger-view", branch = "next" }
syntect = "*"
skim = "*"
#
# Drivers
#
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", branch = "async-await" }
tokio = { version = "*", features = ["full"] }

[profile.release]
lto = true
